"""Type checking for Forge programs after name resolution."""

from .checker import TypeCheckError, TypeCheckResult, TypeTable, check_types
from .types import (
    BOOL,
    DOUBLE,
    INT,
    NULL,
    PATTERN_MISMATCH,
    STRING,
    UNKNOWN,
    VOID,
    ArrayType,
    BuiltinType,
    ClassType,
    EnumType,
    FunctionType,
    InterfaceType,
    NullableType,
    OutcomeType,
    StructType,
    TaskCollectionType,
    TaskType,
    Type,
)

__all__ = [
    "ArrayType",
    "BOOL",
    "BuiltinType",
    "ClassType",
    "DOUBLE",
    "EnumType",
    "FunctionType",
    "InterfaceType",
    "INT",
    "NULL",
    "PATTERN_MISMATCH",
    "NullableType",
    "OutcomeType",
    "STRING",
    "StructType",
    "TaskType",
    "TaskCollectionType",
    "Type",
    "TypeCheckError",
    "TypeCheckResult",
    "TypeTable",
    "UNKNOWN",
    "VOID",
    "check_types",
]
